#page title
page_title                                : Paperless                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6673909586                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id6673909586                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Paperless                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 3.99                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Book to digital pdf, Quick Scan Easy Organize Share

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Karma
your_link                                 : https://www.codewithkarma.com
your_city                                 : Brisbane
email_address                             : karm.singh@outlook.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : CodeWithKarma
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Advanced Scanning Technology
    description                           : High-quality document scanning,  Auto-edge detection and perspective correction, Multi-page document support
    fontawesome_icon_name                 : scanner-image
    
  - title                                 : Versatile Document Handling
    description                           : Scan various document types, receipts, ID cards, books, and more, Batch scanning for multiple documents
    fontawesome_icon_name                 : file

  - title                                 : OCR Technology
    description                           : Extract text from images and scanned documents, Make all your documents searchable
    fontawesome_icon_name                 : text

  - title                                 : User-Friendly Interface
    description                           : Intuitive design for easy navigation, Customizable dashboard for quick access to frequently used features
    fontawesome_icon_name                 : user-group

  - title                                 : Regular Updates and Support
    description                           : Continuous improvements and new features, Responsive customer support
    fontawesome_icon_name                 : headset

faqs                                      :

  - title                                 : How do I search for a file?
    description                           : Search for the file using a name.
    fontawesome_icon_name                 : search

  - title                                 : Do I loose all my data if I delete the app?
    description                           : Yes, all the data stays on your device. However, you can share the pdf file and save it to your files or iCloud.
    fontawesome_icon_name                 : eraser

  - title                                 : How do I delete a Pdf?
    description                           : Open the pdf file details and delete it.
    fontawesome_icon_name                 : trash

  - title                                 : How do I contact for support?
    description                           : You can post on the twitter @CodeWithKarma or you can try to send an email from the app and I will try to respond. 
    fontawesome_icon_name                 : users

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
